---
# File: tls.yml - TLS tasks for Consul

- block:
    - name: Create SSL directory
      file:
        dest: "{{ consul_tls_dir }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755

    - name: Copy CA certificate
      copy:
        src: "{{ consul_tls_src_ca_file }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_ca_cert }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0644
      when: consul_tls_src_ca_file is file
      notify: restart consul

    - name: Copy server certificate
      copy:
        src: "{{ consul_tls_src_server_cert_file }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_cert }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0644
      when: consul_tls_src_server_cert_file is file
      notify: restart consul

    - name: Copy server key
      copy:
        src: "{{ consul_tls_src_server_key_file }}"
        dest: "{{ consul_tls_dir }}/{{ consul_tls_server_key }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0600
      when: consul_tls_src_server_key_file is file
      notify: restart consul

  when: consul_tls_copy_files | bool
